java.lang.InstantiationException: com.jarluo.mybatis.mapper.BlogMapper 	at java.lang.Class.newInstance(Class.java:427) 	at com.jarluo.mybatis.executor.ResultSetHandler.handle(ResultSetHandler.java:19) 	at com.jarluo.mybatis.executor.JvStatementHandler.query(JvStatementHandler.java:30) 	at com.jarluo.mybatis.executor.JvSimpleExecutor.query(JvSimpleExecutor.java:16) 	at com.jarluo.mybatis.session.JvDefaultSqlSession.selectOne(JvDefaultSqlSession.java:40) 	at com.jarluo.mybatis.binding.JvMapperProxy.invoke(JvMapperProxy.java:29) 	at com.sun.proxy.$Proxy0.selectBlogById(Unknown Source) 	at com.jarluo.mybatis.JvBatisTest.main(JvBatisTest.java:14) Caused by: java.lang.NoSuchMethodException: com.jarluo.mybatis.mapper.BlogMapper.<init>() 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.newInstance(Class.java:412) 	... 7 more